name: Testing

on:
  push:
    branches:
      - 'master'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm test
      - name: npm publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.UI_NPM_TOKEN_2023}}